site_name: IDAPython Scripts
theme:
  name: material
nav:
- Home: index.md
- Core:
  - Enumerate Segments: core/enumerate_segments.md
markdown_extensions:
- codehilite
- admonition
- pymdownx.highlight
- pymdownx.superfences
plugins:
- search
